name: "New Conversation"
labels: ["Conversation"]
description: "You want to talk to me and don't mind sharing it with others."
body:
  - type: textarea
    id: detail
    attributes:
      label: Details
      description: "Anything to add?"
      placeholder: "No details."
    validations:
      required: false
